############################################################################
# examples/usb_camera/Makefile
#
############################################################################

include $(APPDIR)/Make.defs
include $(SDKDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_USB_CAMERA_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_USB_CAMERA_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_USB_CAMERA_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_USB_CAMERA)

ASRCS =
CSRCS =
MAINSRC = usb_camera_main.c

include $(APPDIR)/Application.mk
