############################################################################
# examples/usb_image/Makefile
#
############################################################################

include $(APPDIR)/Make.defs
include $(SDKDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_USB_IMAGE_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_USB_IMAGE_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_USB_IMAGE_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_USB_IMAGE)

ASRCS =
CSRCS =
MAINSRC = usb_image_main.c

include $(APPDIR)/Application.mk
